{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kora.fullname" . }}-db
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kora.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "kora.databaseUrl" . | quote }}
{{- end }}
